### ISSUE TITLE
Add frule and rrule for cat

### ISSUE THREAD

**Issue by AzamatB** [JuliaDiff/ChainRules.jl#125]
Related: [#198](https://github.com/FluxML/Zygote.jl/issues/198)

**Comment by oxinabox** [comment]
We have `hcat` and `vcat` but not `cat`.
It should be a fairly simple generalization of them.
And they will be able to be replaced with calls the one for `cat, passing in the dims argument.

**Comment by AzamatB** [comment]
There is a [definition](https://github.com/FluxML/Zygote.jl/pull/378/files) of adjoint for `cat` in Zygote.jl now. So I guess we can borrow it from there.
