### ISSUE TITLE
Change to BlueStyle

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#141]
Talked to @jrevels about this a few months back. And he wasfine with it.
Right now the code is roughly in the intersection of what YASGuide and BlueStyle allow.
Which is pretty large as they overlap significantly.

But given most people maintaining it now are used to BlueStyle, we should use that.

#80 doesn't follow BlueStyle indenting.
And that's fine because the readme says YASGuide.
But we should change that

**Comment by YingboMa** [comment]
I feel like that the BlueStyle is overly restrictive. For instance, I don't see much benefit from sorting imports logically, but it adds a huge burden to developers. I'd vote for stick with the YASGuide.

**Comment by mattBrzezinski** [comment]
It takes about a minute to sort imports alphabetically, and then makes it much easier for anyone to quickly find if a package has been introduced already.

I'm not following along much with this package, or either style guides. But I believe doing small changes like this makes the package seem more put together and professional.

I think little things like this make for a good use case for a Julia linter, and other small tools to help simplify things.

**Comment by YingboMa** [comment]
You could just search in `Project.toml` for packages. I don't see how sorting it helps anyone, especially, for stuff like

```julia
using Dates: Year, Month, Week, Day, Hour, Minute, Second, Millisecond
```


I don't know about Atom, but it is so hard to get those tools to work with Vim or VSCode. If there is a simple way to do it, I will be fine with it. But I feel it adds unnecessary steps and mental effort to do something with little gain.
