### ISSUE TITLE
Update Cholesky and SVD to use Composite

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#151]
`Composite` was made for this case,
but we haven't changed  it over, and it still uses a hack.

- [x] SVD
- [x] Cholesky

**Comment by nickrobinson251** [comment]
definition of Composite in ChainRulesCore
- src https://github.com/JuliaDiff/ChainRulesCore.jl/blob/master/src/differentials/composite.jl
- test https://github.com/JuliaDiff/ChainRulesCore.jl/blob/master/test/differentials/composite.jl

**Comment by nickrobinson251** [comment]
I'd like to take a go at this, to understand better whatsup with `Cmposite`, but will probably need some guidance. Will try to open a PR this weekend.

For SVD, will we have `svd_pullback(Ȳ::Composite{<:SVD})` and then in `getproperty_svd_pullback` change all uses of `NamedTuples` to `Composite`s?

**Comment by oxinabox** [comment]
>  Will try to open a PR this weekend.

It's the weekend.

---

> For SVD, will we have svd_pullback(Ȳ::Composite{<:SVD}) and then in getproperty_svd_pullback change all uses of NamedTuples to Composites?

That sounds right.

The important part to remember about Composites in reverse mode,
is if your primal argument was a struct, then your pullback return is a Composite. 
So that is your `getproperty_svd_pullback`

And conversely:
if the primal return value is a struct, your pullback argument is a Composite.
so that is your `svd_pullback`
