### ISSUE TITLE
handle `uplo` argument for Symmetric

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#178]
Zygote handles the 2 arg function for Symmetric
ChainRules rightnow only handles the 1 arg function

**Comment by sethaxen** [comment]
Should be easy to transfer from Zygote. Actually, of all of the Symmetric/Hermitian rules in Zygote, are there any that just should not be in ChainRules?

**Comment by oxinabox** [comment]
Nope, they all should be.
Only thing that should not be really is things that need to call back into AD (so unrestricted higher ordee functions)
We know how to support that but haven't yet.

Also nonholomorphic things

**Comment by sethaxen** [comment]
Okay, yeah the power series defaults do call `pullback` internally, so I'll hold off on any transfer for now.

**Comment by sethaxen** [comment]
I will transfer over the rrules for the constructor though. Would like to do `Hermitian` at the same time. How in ChainRules should I test an rrule with complex numbers?

**Comment by willtebbutt** [comment]
Same as you would with real numbers, just replace everything with complex numbers, including the seed. `to_vec` _should_ just handle it.
