### ISSUE TITLE
Incorrect chain rule for `abs2`

### ISSUE THREAD

**Issue by MasonProtter** [JuliaDiff/ChainRules.jl#195]
this rule is incorrect for complex arguments: https://github.com/JuliaDiff/ChainRules.jl/blob/2d8b2656c16a38df1a01d698a0bd729d4624ac76/src/rulesets/Base/fastmath_able.jl#L40

It should be restricted to `<:Real` and then preferably have a non-holomorphic complex version defined.

**Comment by oxinabox** [comment]
Cool want to make a PR?
