### ISSUE TITLE
Test against Julia 1.4 with Travis

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/ChainRules.jl#202]
Currently Travis only tests against 1.0 - 1.3 and nightly. It also allows failures on Julia 1.3. We should test against 1.4 and disallow failures on release versions.

**Comment by oxinabox** [comment]
cf. https://github.com/JuliaDiff/ChainRules.jl/issues/149
there is something weird that happens with 1.3 that i do not understand.

**Comment by willtebbutt** [comment]
> I am tempted to change the tests to 1.0, 1, nightly

I think this would be sensible.
