### ISSUE TITLE
Change convention for complex differentiation

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/ChainRules.jl#210]
This issue tracks the necessary changes after https://github.com/JuliaDiff/ChainRulesCore.jl/issues/167 is merged:
- ChainRulesCore:
   - [x] Update `ChainRulesCore.@scalar_rule` to conjugate the partials in `rrule`. (breaking change) (https://github.com/JuliaDiff/ChainRulesCore.jl/pull/170)
- ChainRulesTestUtils:
    - [x] Bump ChainRulesCore compat  (https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/44)
    - [x] Update `ChainRulesTestUtils.test_scalar` to conjugate the derivative when testing `rrule`. (breaking change)(https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/44)
- ChainRules:
   - [x] Add missing tests for rules that take complex arguments (#214, #215)
   - [x] Bump ChainRulesCore, ChainRulesTestUtils, and FiniteDifferences compats (breaking change) (#198)
   - [x] Update non-scalar `rrule`s to follow the new convention (breaking change).
- Zygote:
   - [x] Bump ChainRules compat (https://github.com/FluxML/Zygote.jl/pull/721)
   - [x] Update Zygote's adjoints to stop conjugating to/from ChainRules (https://github.com/FluxML/Zygote.jl/pull/721)

I have local implementations of most of these already.

**Comment by willtebbutt** [comment]
Happy to help out anywhere that it would be useful, but you're probably the best placed to deal with these.

**Comment by oxinabox** [comment]
>  Update Zygote's adjoints to stop conjugating to/from ChainRules (breaking change)

This is not breaking for Zygote.
Its a nonbreaking feature to change what version of ChainRule's it supports

**Comment by sethaxen** [comment]
Good point, thanks. Yes, if Zygote bumps the compat and stops conjugating to/from ChainRules at the same time, this is not a breaking change. I have updated.
