### ISSUE TITLE
no method matching MersenneTwister(::typeof(abs2), ::Array{Complex{Float64},1})

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDiff/ChainRules.jl#227]
I suddenly got a mysterious error on CI from a call to Zygote.gradient
```
LoadError: MethodError: no method matching MersenneTwister(::typeof(abs2), ::Array{Complex{Float64},1})
```
I haven't touched the code that threw the error in a long time so something must have gone wild in Zygote or ChainRules
link to CI failure: https://github.com/baggepinnen/SpectralDistances.jl/runs/840227039#step:4:721
link to failing call: https://github.com/baggepinnen/SpectralDistances.jl/blob/master/test/test_diff.jl#L204 

Probably caused by https://github.com/JuliaDiff/ChainRules.jl/commit/697e7e4e168015d216c86863c5c205f954766ddc

```
julia version 1.4.2
Installed ChainRules ─────────────────── v0.7.5
Installed Zygote ─────────────────────── v0.5.2
Installed ZygoteRules ────────────────── v0.2.0
```

**Comment by mcabbott** [comment]
Should this package test Zygote, to catch such things? 

Possibly just `@test (Pkg.test("Zygote"); true)`, but that takes a while so perhaps better a CI task done after the others, somehow.

**Comment by willtebbutt** [comment]
Ideally we would, but Zygote has a fairly elaborate CI pipeline, so it would take some work to get this set up.

**Comment by mcabbott** [comment]
Why do you say elaborate? https://github.com/FluxML/Zygote.jl/blob/master/.travis.yml looks standard. 

Or the `@test` above would work so long as Zygote was a test dep.

**Comment by simeonschaub** [comment]
We could copy what we do in ChainRulesCore for ChainRules integration tests already. Would be good to have a separate runner for this, so the test suite doesn't take forever to run.

**Comment by willtebbutt** [comment]
>Why do you say elaborate? https://github.com/FluxML/Zygote.jl/blob/master/.travis.yml looks standard.

I guess I was more referring to the fact that they've got a separate gitlab CI run set up when you invoke bors: https://github.com/FluxML/Zygote.jl/blob/master/.gitlab-ci.yml

But I suppose a regular CI run that doesn't handle the GPU stuff would be an improvement over nothing.

**Comment by mcabbott** [comment]
OK, yes hooking up the GPU tests sounds harder. But the basic level would have caught this. 

ChainRulesCore's Cirrus CI at https://github.com/JuliaDiff/ChainRulesCore.jl/blob/master/.cirrus.yml looks like exactly the right sort of thing.

**Comment by CarloLucibello** [comment]
I think this is also hitting me in https://github.com/FluxML/Flux.jl/pull/1264
see error here:
https://travis-ci.org/github/FluxML/Flux.jl/jobs/705291614

**Comment by CarloLucibello** [comment]
+1 on running Zygote tests here as well

**Comment by nickrobinson251** [comment]
Thanks for the report! And thanks @sethaxen for fixing it so fast. ChainRules v0.7.6 should be released any minute and should fix this 🤞 

I opened another issue to discuss the idea of running Zygote tests as part of the ChainRules CI #229

**Comment by baggepinnen** [comment]
My failing CI is now shining bright and green, thanks Seth and Co!

**Comment by DhairyaLGandhi** [comment]
+1 for Zygote tests in ChainRules!
