### ISSUE TITLE
Should we run Zygote tests as part of CI?

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDiff/ChainRules.jl#229]
Raised in https://github.com/JuliaDiff/ChainRules.jl/issues/227#issuecomment-654096195

We could copy what we do in ChainRulesCore for ChainRules integration tests already: https://github.com/JuliaDiff/ChainRulesCore.jl/blob/master/.cirrus.yml Would be good to have a separate runner for this, so the test suite doesn't take forever to run.

The idea is to stress test new rules (e.g. check they're constrained to the right inputs as expected).

**Comment by oxinabox** [comment]
Once ForwardDiff2 gets back up to the latest version of ChainRules we should add it also

**Comment by oxinabox** [comment]
Potentially we should use Github actions instead of CirrusCI,
I think it is faster, esp if we have to end up doing a bunch of these reverse dependency tests.
