### ISSUE TITLE
More linear algebra rules

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/ChainRules.jl#238]
[This paper](https://dl.acm.org/doi/abs/10.1145/3382191) (there seems to be a free earlier version [here](https://notendur.hi.is/jonasson/greinar/blas-rmd.pdf)) has a number of reverse-mode rules, in particular for BLAS and LAPACK subroutines. Saw a bunch we don't have in there (see the tables).

**Comment by willtebbutt** [comment]
@sethaxen would you mind moving this info to #117 so that we can close this in favour of that? (Incidentally, we might need to rename that issue, it's not quite descriptive of what we're after)
