### ISSUE TITLE
ChainRules.ignore

### ISSUE THREAD

**Issue by willtebbutt** [JuliaDiff/ChainRules.jl#256]
[Zygote.ignore](https://fluxml.ai/Zygote.jl/dev/utils/#Zygote.ignore) is a lovely piece of functionality that we aught to be able to provide at the `ChainRulesCore`-level. It would also be _incredibly_ straightforward to implement.

It'll only work properly with Zygote-like ADs ofc, but it's an improvement over it not working at all.

**Comment by oxinabox** [comment]
probably would not go in any rulesets but in some other new file.

**Comment by gxyd** [comment]
Hi,

If noone is working on this, can I may be try to work on this?

**Comment by willtebbutt** [comment]
I don't believe that anyone is actively working on this. Please go ahead -- happy to review :)

**Comment by oxinabox** [comment]
Closing in favour of doing this in CRC.
https://github.com/JuliaDiff/ChainRulesCore.jl/issues/470
