### ISSUE TITLE
New Non-Diff Rules can cause Zygote to change keyword arguments

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/ChainRules.jl#257]
MWE:

```julia
using Zygote

struct Type1{VJP}
  x::VJP
end

struct Type2{compile}
  Type2(compile=false) = new{compile}()
end

function loss_adjoint(θ)
  sum(f(sensealg=Type1(Type2(true))))
end
function f(;sensealg=nothing)
  @show "entry",sensealg
  return rand(100)
end

loss_adjoint([1.0])
Zygote.gradient(loss_adjoint,[1.0])
```

Before:

```
("entry", Type1{Type2{true}}(Type2{true}()))
("entry", Type1{Type2{true}}(Type2{true}()))
```

After:

```
("entry", Type1{Type2{true}}(Type2{true}()))
("entry", Base.OneTo(true))
```

I'm going to search for that rule.

**Comment by oxinabox** [comment]
We know it is ChainRules  0.7.16 doing it because going back to 0.7.15 fixes it.
But its super weird since `@non_differentiable` doesn't even support kwargs.
(Probably something that should be changed, it should accept them as `kwargs...` and then pass them on)

**Comment by oxinabox** [comment]
Underlying cause is:
https://github.com/JuliaDiff/ChainRulesCore.jl/issues/213
