### ISSUE TITLE
@non_differentiable rand

### ISSUE THREAD

**Issue by nmheim** [JuliaDiff/ChainRules.jl#262]
Really happy that ChainRules now has a `@non_differentiable` macro! Unfortunately it includes all `rand` methods, which is a bit too restrictive... there was a similar discussion about this in https://github.com/FluxML/Zygote.jl/pull/234 .

MWE:
```julia
using Random
using Zygote

struct Normal
    μ
    σ
end

Random.rand(d::Normal) = randn()*d.σ + d.μ
f(a,b) = rand(Normal(a,b))
gs = Zygote.gradient(f,2,2) # returns (nothing,nothing) with ChainRules > 0.7.15
```

**Comment by willtebbutt** [comment]
Lol, yeah, we really shouldn't have done that 🤦 It was literally _the_ motivating for a more flexible `@non_differentiable` / `@nograd` macro.

A PR modifying the implementation would be very welcome.

**Comment by nmheim** [comment]
Thanks for merging this so quickly!
