### ISSUE TITLE
Matrix-Vector, Vector-Matrix, Vector-Vector product

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#276]
I think this can probably use the same rules as out Matrix-Matrix products,
but it wants some tests to confirm.
Might even be just swapping `AbstractMatrix` for `AbstractVecOrMat`

A lot of these products are nonsense.
but that is ok, they will error on the primal pass

**Comment by gxyd** [comment]
Though a vector-matrix product is valid and can be computed. But in the rule definition `mul!` is used, documentation of which says:
```
mul!(Y, A, B) -> Y

Calculates the matrix-matrix or matrix-vector product $AB$
and stores the result in Y, overwriting the existing value of Y.
Note that Y must not be aliased with either A or B.
```
So it be ok from the primal computation side, but would error while computing its derivative.

**Comment by gxyd** [comment]
@oxinabox anything on the above?

**Comment by oxinabox** [comment]
I don't understand the problem.

`mul!` works fine for any mixture of matrixes, vectors, and numbers, that doesn't result in a dimension mismatch.
Except for `Union{Transpose{<:Vector}, Adjoint{<:Vector}}`, `*` `Vector` since that one yeilds a scalar.

But in anycase for things that don't work by relaxing signatures we just write a seperate rule, and it is not a problem?
