### ISSUE TITLE
uplo variable missing for Cholesky rrule

### ISSUE THREAD

**Issue by wupeifan** [JuliaDiff/ChainRules.jl#285]
https://github.com/JuliaDiff/ChainRules.jl/blob/master/src/rulesets/LinearAlgebra/factorization.jl#L89-L98

The Cholesky composite includes an "uplo" variable indicating whether the upper triangular or the lower one is stored. However, in the returned structure, there are only values instead of types. Returning a `U = some_matrix` won't set the "uplo" variable to "U".

**Comment by willtebbutt** [comment]
Should we expect this to matter anywhere? i.e. do we actually need to know the value of `uplo` in the composite that is returned from this?

**Comment by wupeifan** [comment]
It's a bit indirect. I have a function `g(A)` where `A` is a Cholesky composite object, `A = f(x)`.  I'm defining a custom rrule for function `f`, given the sensitivities pulled back from `g`. Without pulling back whether the shape of `A` is upper triangular or lower triangular, it's hard to write the custom rrule for `f`. Hard to find an MWE for it though, @willtebbutt

**Comment by nickrobinson251** [comment]
Any fields not explictly present in the `Composite` are treated as being set to `Zero()`.
https://www.juliadiff.org/ChainRulesCore.jl/dev/api.html#ChainRulesCore.Composite

E.g.
```julia
julia> using ChainRules, LinearAlgebra

julia> X = let x = rand(2,2); x*x'+I; end
2×2 Array{Float64,2}:
 1.74036   0.381175
 0.381175  1.22639

julia> U, pb = rrule(getproperty, cholesky(X), :U);

julia> U
2×2 UpperTriangular{Float64,Array{Float64,2}}:
 1.31923  0.288938
  ⋅       1.06907

julia> dg, dC, dsym = pb(rand(2,2))
(Zero(), Composite{Cholesky{Float64,Array{Float64,2}}}(U = [0.7750864029306548 0.41843691409839967; 0.0 0.9025528336114459],), DoesNotExist())

julia> dC
Composite{Cholesky{Float64,Array{Float64,2}}}(U = [0.7750864029306548 0.41843691409839967; 0.0 0.9025528336114459],)

julia> dC.uplo
Zero()
```

**Comment by willtebbutt** [comment]
Does Nick's response answer your question? And is there a reason that you can't just capture the `uplo` field during the forwards-pass over `f`?

I do wonder whether we've got the field names of the `Cholesky` composite slightly wrong -- it's possible that the field `U` should be called `factors` instead, since that's the name of the field of a `Cholesky`.

**Comment by wupeifan** [comment]
> Does Nick's response answer your question? And is there a reason that you can't just capture the uplo field during the forwards-pass over f?

Yes and no, as the problem exactly I am having now is `dC` from pullback doesn't include the information in primal. Currently what I am doing is capturing the uplo field in the primal, but I don't know whether that's ideal or not.

**Comment by willtebbutt** [comment]
> Currently what I am doing is capturing the uplo field in the primal,

As in you're capturing it in the closure return from the forwards pass? If so, then yes, that's ideal and is very much intended use :)

**Comment by oxinabox** [comment]
`Composites` are differentials, they live in a (co-)tangent space.
They need to be purely vector space elements, which boils down to all their fields need to have `+` and `zero` and scalar multiplication defined on them; and need to be the differentials for the corsponding items in the primal  space.
(Which for `uplo` strictly speaking should be `DoesNotExist`, but any `AbstractZero` will do).

I don't understand your problem exactly, just that the solution is not store information in the Composite on that field.
If you want you can check `hasproperty(comp, :U)` and `hasproperty(comp, :L)` to know which we have defined.
Though we have both defined in practice -- the other one is just going to be set to `Zero()`

**Comment by wupeifan** [comment]
>just that the solution is not store information in the Composite on that field.
OK, if it is not a good idea to store that info in `dC` then I'll just do what I am doing now by capturing it from the primal. Feel free to close this then

**Comment by wupeifan** [comment]
Sorry, one more question: the sensitivities should be 0 for the zero-elements in the upper triangular matrix. That's by the definition of the upper triangular matrix. For example, if `A` is upper triangular and you pull back `sum(A)`, it probably will pullback a full matrix, but we only need the upper triangular part. Hence I think `uplo` should still be the same as the type you pass in.

**Comment by oxinabox** [comment]
> Sorry, one more (very slight) argument: the sensitivities should be 0 for the zero-elements in the upper triangular matrix. That's by the definition of the upper triangular matrix. 

They will be, because we will return a `UpperTriangular` matrix.
https://github.com/JuliaDiff/ChainRules.jl/blob/bbe68ccbcd26971e0254607e01dc1f5c8be1d6c1/src/rulesets/LinearAlgebra/factorization.jl#L91

As an aside:  i am pretty sure if Ȳ has nonzeros in its upper triangle, that means that some operation performed later (i.e. earliy in the reverse tape) has been giving back an  incorrect gradient. Since  there is no way for those primal zero values interact with anything in a way that can give them non-zero gradients.

**Comment by nickrobinson251** [comment]
i don't think there is anything to do here, so will close this. (But please comment if i'm mistaken!)
