### ISSUE TITLE
use `sincos` in rules for sin and cos

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#291]
We could use `sincos` to comput sin and cos at the same time for the rules for sin and cos.

e.g.

```julia
function rrule(::typeof(sin), x::Number)
    sinx, cosx = sincos(x)
    sin_pullback(dy) = (NO_FIELDS, cosx*dy)
    return sinx, sin_pullback
end
```

With definition above:
```julia
julia> @btime rrule(sin, x)[2](2.5)
  1.255 ns (0 allocations: 0 bytes)
(Zero(), 2.193956404725932)
```

vs current master:
```julia
julia> @btime rrule(sin, x)[2](2.5)
  4.805 ns (0 allocations: 0 bytes)
(Zero(), 2.193956404725932)
```

I was reminded of this because it is one of the textbook reasons we didn't do #289 from the start.
But apparently we have never written this rule.

I think this would be a very nice first issue because 
 - It already has tests
 - It is writing the other 3 versions of the code i wrote above (`rrule` for `cos`, `frule` for `cos`, `frule` for `sin`)
 - and checking the benchmarks.

**Comment by GiggleLiu** [comment]
Haha, nice catch!
