### ISSUE TITLE
Drop SpecialFunctions dependency

### ISSUE THREAD

**Issue by stevengj** [JuliaDiff/ChainRules.jl#319]
The next release of SpecialFunctions will include ChainRulesCore rules: JuliaMath/SpecialFunctions.jl#238

Do we need to synchronize releases to prevent Julia from complaining about overwritten method definitions?  That is, once we update SpecialFunctions, do a new release of ChainRules shortly afterwards?

cc @devmotion

**Comment by devmotion** [comment]
One could follow @oxinabox's suggestion in https://github.com/JuliaMath/SpecialFunctions.jl/pull/238#issuecomment-692900690 and introduce a check in ChainRules and releasing it before the next release of SpecialFunctions.

**Comment by oxinabox** [comment]
We should do that then next breaking release of ChainRules.jl drop the dependency and the rules.
