### ISSUE TITLE
 Zygote Integration testing

### ISSUE THREAD

**Issue by willtebbutt** [JuliaDiff/ChainRules.jl#326]
Is there a reason that [we're testing against Julia 1.4](https://github.com/JuliaDiff/ChainRules.jl/blob/22eddb479062838b7a3e5541cd94a29360eb8617/.github/workflows/IntegrationTestZygote.yml#L14), or is it an oversight?

**Comment by sethaxen** [comment]
I think the workflow was created when 1.4 was the latest release, and I hardcoded it instead of making it `1`. It should be updated for sure.

**Comment by oxinabox** [comment]
as I recall: Zygote was broken on 1.5 for a long time. now that it is fixed on 1.5 we can go back to testing on 1.
