### ISSUE TITLE
Remove ChainRulesTestUtils and FiniteDifferences from direct dependencies

### ISSUE THREAD

**Issue by matbesancon** [JuliaDiff/ChainRules.jl#332]
Having these as package dependencies and not test dependencies makes CR a heavier dependency to have.
From what I understand they are in the deps only to be able to specify versions? If that's the case they could be replaced with a test/Project.toml

**Comment by nickrobinson251** [comment]
Looks like FiniteDifferences is already a test-only dependency, but it seems ChainRulesTestUtils is listed as a main dependency. I think this is likely just a mistake - a PR to remove it from the `deps` section would be welcome

**Comment by oxinabox** [comment]
Can't move them the `test/Project.toml` as that would break Julia 1.0 compat.
But can move them into `extras` -- the main compat still works on things in `extras`.

They were added as direct dependencies by mistake.
This has happened before.
Probably added just for a quick test of something, but forgotten to discard that change before committing,
and missed during code-review.
