### ISSUE TITLE
Update tests to use new easier testing mechanism

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#360]
We need to follow up on https://github.com/JuliaDiff/ChainRulesTestUtils.jl/pull/116
and take advantage of the improvements.

Here is a list of  files.
Some of there are probably really easy since they only use `test_scalar` so nothing is needed.
Others we should take this chance to clean them up more broadly since they are also doing other things like retesting the primal output, even though `test_rrule` does that now; or not even using the testing functionality at all.

- Base
    - [x] array.jl
    - [x] arraymath.jl
    - [x] base.jl
    - [x] evalpoly.jl
    - [x] fastmath_able.jl
    - [x] indexing.jl
    - [x] mapreduce.jl
- LinearAlgebra
    - [x] blas.jl
    - [x] dense.jl
    - [ ] factorization.jl
    - [x] matfun.jl
    - [x] norm.jl
    - [x] structured.jl
    - [x] symmetric.jl
 - Random
    - [x] random.jl
 - Statistics
    - [x] statistics.jl
 - packages
    - [x] NaNMath.jl
    - [x] SpecialFunctions.jl

**Comment by oxinabox** [comment]
For the SpecialFunctions.jl file we can just copy the tests that I already fixed over at 
https://github.com/JuliaMath/SpecialFunctions.jl/pull/300

**Comment by oxinabox** [comment]
Our rules for NaNMath.jl have no tests.  😞 
Next breaking change we should delete those rules. Noone uses that package any more AFAIK

**Comment by willtebbutt** [comment]
😬

**Comment by oxinabox** [comment]
random.jl doesn't use `rule_test` because it is just checking things are all returning zeros.

**Comment by oxinabox** [comment]
I think that is every PR openned

**Comment by oxinabox** [comment]
across all the PR s the number of lines in the test directory went from `10,629`, down to `9,197`
so a net decrease of 1432 lines.
Plus probably improved clarity of another 1432 lines by decreasing number of arguments
