### ISSUE TITLE
stability of primal when testing eigen

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#379]
See https://github.com/JuliaDiff/ChainRules.jl/pull/375#discussion_r577908632_

In short, tests started failing with huge values like 10^5 in the output of FDM.
Fixing the seed fixes it, but replacing `randn(T, n, n)` with `randn(T, n, n,) .+ 5.0`  seemed to fix it robustly.

@willtebbutt said:
> My suspicion would be that the eigenvalues are flipping around or something?

@sethaxen said
> It could be, but the major source of instability I saw was in the phase of the eigenvectors. The convention LinearAlgebra uses (from LAPACK) is that the entry with the largest magnitude in each eigenvector is rotated to be positive real or negative real, whichever is nearest. So it could become unstable if another entry was close to that one in magnitude. So one way might be to do something like this:
> ```julia
> V = hcat(Random.shuffle([normalize((x .+ 1e-2 .* randn.(ComplexF64)) * sign(randn(ComplexF64))) for x in eachcol(Matrix{Float64}(I, n, n))])...)
> ```
> which creates an identity matrix, adds small random complex numbers to all entries, applies a random phase convention to each eigenvector, then normalizes them. The eigenvectors are then shuffled and made columns of a new matrix. This produces one where the element with the largest magnitude is well-separated from the rest. With a suitable set of eigenvalues, perhaps this would make a well-behaved primal.

**Comment by willtebbutt** [comment]
Seth is probably right -- he knows more about this stuff than I do.
