### ISSUE TITLE
combining exp and tr cause setindex error from Zygote

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDiff/ChainRules.jl#380]
this is because Zygote is using `FillArray` but the pullback implementation here assumes the gradient is mutable (so it has `setindex!`) , not sure why Zygote's `tr` rule is not dispatched to ChainRules.

https://github.com/JuliaDiff/ChainRules.jl/blob/master/src/rulesets/LinearAlgebra/matfun.jl#L236

---

I haven't followed the development of Julia AD in the last few months, and now I find these new packages are incredible! But I think this issue is related to something hasn't been well discussed yet: the convention of whether the gradient should be mutable or not, or both. Also sometimes, we want it to be mutable for various reasons,
there is no mechanism to explicitly guarantee this, or maybe should always use BangBang to mutate gradients in rrule? I feel there should be more clarification of the gradient
type interface in docs too, but this might need more discussion

---

XRef: #46

**Comment by sethaxen** [comment]
For `rrule`s limited to `StridedMatrix` inputs and outputs, I've been implementing them with the assumption that a user provides `StridedMatrix` cotangent to the pullback. This is "correct", but we can't always count on it. The easy fix here is to modify the `rrule` to call `Matrix` on the cotangent so it's not just assumed and actually enforced. I'll open a PR.

**Comment by Roger-luo** [comment]
> This is "correct", but we can't always count on it.

I see. Yeah, I guess `StrideMatrix` currently serves partially as a poor man's "trait" for strided mutable matrices, I can see when there could be cases where `rrules` defined outside of this `Union` type that won't work. 

> The easy fix here is to modify the rrule to call Matrix on the cotangent so it's not just assumed and actually enforced. I'll open a PR.

Thanks!
