### ISSUE TITLE
rules for `repeat` are missing

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaDiff/ChainRules.jl#383]
Some of them can be ported over from Zygote. 

cf. https://github.com/FluxML/Zygote.jl/issues/906
https://github.com/FluxML/Zygote.jl/blob/956cbcf3c572c0eb09c146189bb38b1b434634ff/src/lib/array.jl#L130

**Comment by Dsantra92** [comment]
Can I take over this issue?

**Comment by willtebbutt** [comment]
Please do :) Happy to review a PR resolving this!

**Comment by mzgubic** [comment]
Yes, sure, you are very welcome to

**Comment by willtebbutt** [comment]
It would be great if you could do it in two parts:
1. port across the current `repeat` rules from `Zygote`.
2. add the missing rules.

Doing it in two steps will make it really easy for us to review :)

**Comment by cossio** [comment]
Bump.

Please note that the rules for Zygote are incomplete: https://github.com/FluxML/Zygote.jl/issues/950

**Comment by nickrobinson251** [comment]
PRs welcome! The docs should help introduce the idea of `rrule`s and how to write them, for anyone who want to contribute :) (https://juliadiff.org/ChainRulesCore.jl/dev/#frule-and-rrule)

**Comment by mzgubic** [comment]
I've recommended this issue to https://github.com/Wimmerer (can't seem to @ him) whom I will (likely) co-mentor for his `GraphBLAS x ChainRules` GSoC project

**Comment by mcabbott** [comment]
Zygote has several different implementations for the repeat gradient, https://github.com/FluxML/Zygote.jl/blob/2468e2f1f787e42e9c3d0aa93cec58a0488f8573/src/lib/array.jl#L149-L173 , and the one you're timing seems to be 300x slower than the other one:
```julia
julia> xs = collect(1:100)

julia> y_in7, back_in7 = Zygote.pullback(xs) do x  # same as above
           repeat(x, inner=(7, ))
       end;

julia> @btime back_in7($(ones(size(y_in7))));
  144.166 μs (4202 allocations: 132.14 KiB)

julia> y_out7, back_out7 = Zygote.pullback(xs) do x  # also uses slow implementation
           repeat(x, outer=(7, ))
       end;

julia> @btime back_out7($(ones(size(y_out7))));
  144.167 μs (4202 allocations: 132.14 KiB)

julia> y_vec7, back_vec7 = Zygote.pullback(xs) do x
           repeat(x, 7)
       end;

julia> @btime back_vec7($(ones(size(y_vec7))));  # uses reshape & sum
  545.857 ns (13 allocations: 1.19 KiB)

julia> y_out7 ≈ y_vec7
true

julia> @btime repeat($xs, inner=(7,));  # forward pass for comparison
  453.046 ns (1 allocation: 5.62 KiB)

julia> @btime repeat($xs, 7);
  281.323 ns (1 allocation: 5.62 KiB)
```
The fast one just uses `reshape` & `sum`. That ought to be possible for all cases, I think. And the result would then probably work well on `CuArray`s, too.

(But also, why are you using `repeat` in something you want to be fast? It always seems wasteful to make many copies of the same data just to make some array the right shape, especially if you aren't then going to mutate it... can't you use broadcasting to do it lazily?)

**Comment by cossio** [comment]
Doesn't https://github.com/JuliaDiff/ChainRules.jl/pull/460 close this? 
Note that https://github.com/FluxML/Zygote.jl/issues/950 works now.
