### ISSUE TITLE
Numerical precision of primal not respected for SpecialFunctions.jl

### ISSUE THREAD

**Issue by torfjelde** [JuliaDiff/ChainRules.jl#402]
Several methods from SpecialFunctions.jl are not respecting the numerical precision of the primal:
```julia
julia> using ChainRules, SpecialFunctions

julia> y, ȳ = ChainRules.rrule(SpecialFunctions.erf, 1.0f0)
(0.8427008f0, SpecialFunctions.var"#erf_pullback#12"{Float32}(1.0f0))

julia> ȳ(1.0f0)[2]
0.41510750774498784
```

I'm guessing this is because the rules were originally copy-pasted from DiffRules.jl which suffers from the same issue: https://github.com/JuliaDiff/DiffRules.jl/pull/55.

I think I'm currently of the opinion that the best way to fix this is to copy-paste the constants from e.g. StatsFuns.jl to remove most of the promotions, and then I guess we'll have to use `oftype` for the remainders.

Is there a better solution?

Btw, I know this related to other issues, e.g. #232, but to me it seems like this particular case is non-ambiguous and can be easily fixed so might as well do it asap:)

**Comment by devmotion** [comment]
The differentials were moved to SpecialFunctions (https://github.com/JuliaMath/SpecialFunctions.jl/pull/238) and are only loaded from ChainRules if an old version of SpecialFunctions without them is used. So all problems have to be fixed there as well.

**Comment by devmotion** [comment]
> I think I'm currently of the opinion that the best way to fix this is to copy-paste the constants from e.g. StatsFuns.jl to remove most of the promotions

Instead of copy-pasting the definitions one could just use `oftype` (as you suggested) or move the constants to a separate package (MathConstants.jl? StatsConstants.jl?). BTW log-related constants live in LogExpFunctions now and are only reexported by StatsFuns.

**Comment by torfjelde** [comment]
> The differentials were moved to SpecialFunctions 

Ah, my bad! Should I just close this and open one over there then? Though I guess the rules also needs to be changed here.

> Instead of copy-pasting the definitions one could just use oftype (as you suggested) or move the constants to a separate package (MathConstants.jl? StatsConstants.jl?). 

I was sort of surprised to find that these were in fact not all in one package, so I would be cool with that. Would be suuuper-lightweight too. Initially I thought "eh, it's dependent on the stats packages actually using this", but I guess we could just start using it AD-frameworks immediately.

> BTW log-related constants live in LogExpFunctions now and are only reexported by StatsFuns.

Cool :+1: But StatsFuns also has its own constants, etc. so it's a bit spread around.

**Comment by mzgubic** [comment]
We are removing the SpecialFunctions rules in this package, have you transferred the issue?
