### ISSUE TITLE
Should we be reexporting ChainRulesCore.jl?

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#415]
Right now we reexport ChainRulesCore.jl
this was on the basis that AD package should depend only on ChainRules.jl not on ChainRulesCore.
But it feels more natural to me for AD packages to depend on both.
and it gives a bit more control on compat

**Comment by willtebbutt** [comment]
What sort of thing would package maintainers be able to do that they can't do now if we don't re-export?

**Comment by oxinabox** [comment]
It wouldn't change much at all.
Except it would mean a breaking change to ChainRulesCore would not nesc be a breaking change to ChainRules.jl
though I don't know how that is possible.

**Comment by willtebbutt** [comment]
Ahh I see. Okay, well I don't have an especially strong opinion on the matter -- seems to me that the current approach is probably fine though.

**Comment by mzgubic** [comment]
One practical issue with this came up when renaming ChainRulesCore differential types, i.e. the `@reexport` macro does not reexport deprecated bindings, see https://github.com/simonster/Reexport.jl/issues/28.
