### ISSUE TITLE
Statically determine whether rule exists

### ISSUE THREAD

**Issue by phipsgabler** [JuliaDiff/ChainRules.jl#43]
Is there a more reasonable way to statically determine whether a function has a rule (with a certain number of arguments) than the following:

```julia
@generated function hasfrule(f::F, ::Val{N}) where {F, N}
    args = fill(zero(Real), N)
    ChainRules.frule(Core.Compiler.singleton_type(f), args...) === nothing ? :false : :true
end
```

Because currently, you return `nothing` as fallback, so I see no other possibility than just calling the function.  I imagined there might be something generated by the rule definition macro, but found nothing.

Or is there an important reason not to (be able) to perform such a check?

**Comment by willtebbutt** [comment]
> Or is there an important reason not to (be able) to perform such a check?

I can't think of any particular reason one _shouldn't_ be able to perform the check, and I can't immediately think of a cleaner solution than the one above under the current implementation. Could you explain a bit more why you're interested in being able to do this?

**Comment by phipsgabler** [comment]
I'm working on a project using Cassette and thought I might need it some time, but now it's more a point of principle.  I'll come back if I actually have a concrete use case :)

**Comment by willtebbutt** [comment]
> I'll come back if I actually have a concrete use case :)

Sounds good. I've also wondered about this myself a bit, but I've been unable to come up with a compelling reason to sort it out. Would be very interested to find one :)

**Comment by oxinabox** [comment]
What do you mean `statically` ?  Julia is not a AOT Static Language.
I don't think that is a legel `@generated` function.

It depends on functions that might not exist yet when it is defined.
Like if some package like say Stheno,
adds new Rules for it's GP kernals.
then Chain Rules will load that definition of `hasfrule`
when Stheno loads ChainRules.
but its new Rule is not defined until later in that package.

**Comment by jrevels** [comment]
@oxinabox is right.

The supported way to use ChainRules isn't to check for rules ahead of time, but actually call `frule`/`rrule` at runtime, then falling back to AD if no rule is found (e.g. `nothing` is returned).

If you don't have actual arguments available, you can use perform reflection at runtime (via e.g. `methods`) to answer the question in the OP.

**Comment by phipsgabler** [comment]
@oxinabox 	By "static", I meant as soon as I have a type, and not only when I actually call the function.  I previously used DiffRules, which has `diffrule` and `hasdiffrule` -- but that only works on symbols and `Expr`s.

As to whether that generated function is legal -- I don't know, I just wrote it and tried it on a few cases; what would speak against it?  The case when you define a method after the generation?

@jrevels 	I considered using `methods` before, but gave up thinking about it. Since there _is_ a method for every function with every argument structure, I couldn't think of a way to distinguish them.

**Comment by oxinabox** [comment]
> The case when you define a method after the generation?

Yes. It is depending on global state -- the method table.
Generated functions are not really allowed to do this except in limited cases.
Behavour is undefined if they do.
Just because it works does not mean it is garenteed to work.
Odds are this  will not break until you call `hasdiffrule` on something before you define the diffrule for it. (Though it may even work then  because the compiler recompiles `@generated` functions when it feels like it)
But that is a implementation detail and can change even in a patch release of julia.
