### ISSUE TITLE
regression: "no method matching ChainRulesCore.ProjectTo" when calling reverse on a vector of functors

### ISSUE THREAD

**Issue by fedario** [JuliaDiff/ChainRules.jl#518]
Hi,
I'm experiencing a method error I cannot explain.
When I run the following code with [d360d2e6] ChainRulesCore v1.3.0 I get an error:

```Julia
using Flux

m = [
    Dense(2, 2),
    Dense(2, 2),
]

function f(x)
    sum(
        reverse(m)[1](x)
    )
end

gradient(f, [4., 4.])
```

```
ERROR: LoadError: MethodError: no method matching ChainRulesCore.ProjectTo(::Dense{typeof(identity), Matrix{Float32}, Vector{Float32}})
Closest candidates are:
  ChainRulesCore.ProjectTo(::Tridiagonal{T, V} where V<:AbstractVector{T}) where T<:Number at ~/.julia/packages/ChainRulesCore/Voykb/src/projection.jl:382
  ChainRulesCore.ProjectTo(::Bidiagonal{T, V} where V<:AbstractVector{T}) where T<:Number at ~/.julia/packages/ChainRulesCore/Voykb/src/projection.jl:355
  ChainRulesCore.ProjectTo(::UnitLowerTriangular) at ~/.julia/packages/ChainRulesCore/Voykb/src/projection.jl:336
  ...
```
I do not get this error when I use
[d360d2e6] ChainRulesCore v0.10.13

Could this be related to this?
https://github.com/FluxML/Zygote.jl/pull/1051

Edit:
I tried adding the relevant @adjoint that was removed in the PR linked above:

```Julia
Flux.@adjoint function reverse(x::AbstractArray, args...; kwargs...)
    _reverse(t) = reverse(t, args...; kwargs...)
    _reverse(x), Δ->(_reverse(Δ), map(_->nothing, args)...)
end
```
And it works.

versions:
Julia v1.6.2
[587475ba] Flux v0.12.6

**Comment by oxinabox** [comment]
Deleting it from around here
https://github.com/JuliaDiff/ChainRules.jl/blob/master/src/rulesets/Base/array.jl#L305
Should do the trick.
Deleting both the `ProjectTo` and the `project` call below.
And adding a test.

Similar could be done for `circshift`, a bit below that.

I think just a bit of over keen application of the pattern when it was introduced.

**Comment by mcabbott** [comment]
Rule is from #489. 

Agree that maybe there's no need to project, if we just trust that whatever the next operation is will have handled it. Maybe we need to audit how many others are like this.

**Comment by oxinabox** [comment]
Would be a good little PR.

I am off to bed now, I will either review a PR tomorrow, or I will fix it myself if one is not made.

**Comment by mcabbott** [comment]
FWIW, applying these to structured matrices does this:
```
julia> reverse(Diagonal([1,2,3]))
3×3 Diagonal{Int64, Vector{Int64}}:
 3  ⋅  ⋅
 ⋅  2  ⋅
 ⋅  ⋅  1

julia> reverse(UpperTriangular([1 2; 3 4]))
ERROR: ArgumentError: cannot set index in the lower triangular part (2, 1) of an UpperTriangular matrix to a nonzero value (2)

julia> circshift(Diagonal([1,2,3]), (1,0))
ERROR: ArgumentError: cannot set off-diagonal entry (1, 3) to a nonzero value (3)

julia> circshift(collect(Diagonal([1,2,3])), (1,0))  # what you might have expected
3×3 Matrix{Int64}:
 0  0  3
 1  0  0
 0  2  0
```
