### ISSUE TITLE
rrule for `eachslice`

### ISSUE THREAD

**Issue by ToucheSir** [JuliaDiff/ChainRules.jl#556]
Putting this here first to judge interest and whether or not it could exist in ChainRules (vs being Zygote-specific). The biggest benefactor I can think of is https://github.com/FluxML/Flux.jl/blob/v0.12.8/src/layers/recurrent.jl#L85, which currently incurs an O(N) allocation for every timestep because of Zygote's `view` adjoint.

**Comment by mcabbott** [comment]
Zygote does have a rule, https://github.com/FluxML/Zygote.jl/pull/896, but it could easily move here.

**Comment by ToucheSir** [comment]
Woops, I completely missed those somehow!
