### ISSUE TITLE
Do ChainRules support differentiating aggregate types with respect to aggregate types?

### ISSUE THREAD

**Issue by parth-07** [JuliaDiff/ChainRules.jl#568]
I was reading the documentation for ChainRules. It isn't exactly clear to me if ChainRules can support differentiating aggregate types with respect to aggregate types or if it plans to support them in the near future.
By aggregate types, I mean class/structure that may contain data members of class/structure types.
Please help me clear this doubt of mine. Please also guide me to the right place if GitHub issue isn't a right place to ask this question.

**Comment by mcabbott** [comment]
At least for reverse mode, it is always thinking about derivatives of some real-valued output (like a loss function) with respect to some `x`, and this `x` may be an arbitrarily complicated struct.

What you might be asking is: Can we construct a Jacobian for `y = f(x)` where `y` is also a complicated struct. For vector `x` & `y`, this matrix is made by calling the pullback once for every element of `y`, and each of those calls is something ChainRules understands. I think that would still be true for struct `y`, but what type the result should be seems complicated, some thoughts here: https://github.com/FluxML/Zygote.jl/issues/564

**Comment by oxinabox** [comment]
I think the answer is yes, but you would need give an example to be clearer.
We don't support jacobians directly at all.
But do support computing vector jacobian products / tangents and jacobian transpose vector products / cotangents for functions of arbitrary julia structures to arbitrary julia structures.

Assembling those into a jacobian (which i guess must be defined as some object that overloads `*` appropriately) is not something this package currently does.

**Comment by mzgubic** [comment]
Correct, this is what `Tangent` is used for, representing tangent types w.r.t. custom structs.

See e.g. https://github.com/JuliaDiff/ChainRules.jl/blob/13a362c4b5069c6a83f936d9d9d8821e566232bb/src/rulesets/LinearAlgebra/structured.jl#L38-L49
where `diagview` will take a `Tangent{Diagonal}` (i.e. receiving `Tangent` in the pullback). The other example is in the docs, (i.e. returning a `Tangent` from the pullback) https://juliadiff.org/ChainRulesCore.jl/stable/rule_author/example.html#The-rrule

**Comment by parth-07** [comment]
Thank you so much for all the replies. The reply helped a lot. I understand the concept so much better now. 
But I am still convinced that we can only represent scalar type with respect to struct types using `Tangent{P}`. 

Please correct me if am wrong somewhere. 

Please consider this code snippet:
```julia
struct Foo
  a::Float64
  b::Float64
end
```
`Tangent{Foo}` should have the following structure:

```julia
struct Tangent{Foo} 
  a::Float64
  b::Float64
end
```

Here, if we consider that `d_foo::Tangent{Foo}` represents the derivative of some scalar type variable `y` with respect to a variable `foo:Foo`. Then we can comprehend `Tangent{Foo}` as follows:

```julia
Tangent{Foo} d_foo;
d_foo.a # derivative of y with respect to foo.a
d_foo.b # derivative of y with respect to foo.b
```

`Tangent{P}` type representation would not work if the `y` type is an aggregate type as well. To give a more concrete example. Please consider this: 

```julia
struct Bar 
  c::Float64
  d::Float64
end
```

Now, if we want to represent derivative of `bar::Bar` with respect to `foo:Foo`, then `Tangent` type should be similar to this: 

```julia
# 'Bar:Foo' notation is only used to describe that 'Tangent' type will depend on both Bar
# and Foo
struct Tangent{Bar:Foo}
  c::Tangent{Foo}
  d::Tangent{Foo}
end
```

And yes, we can describe rules for functions that take structs as parameters and returns a struct as well. But in this case, it seems we generally assume that all the derivatives are of the form 'scalar' with respect to 'someOtherType'. 

Please help me to understand the answer to the following question better:

- I understand that can create our own structs to represent derivatives of aggregate types with respect to aggregate types, and then use them in our rules. Similar to `Tangent{P}` idea, can we request ChainRules to create this struct for us? If yes, then where can I find the rules that are used to create this struct.

**Comment by oxinabox** [comment]
>  if we want to represent derivative of bar::Bar with respect to foo:Foo

Here we might have to actually take some care with terminology.
*derivative* is only defined with respect to functions ℝ→ℝ.
A function from `Foo` to `Bar` is isomorphic to a function: ℝ²→ℝ².
Derivatives are not defines on those.
Thus your question is ill poised.

*Partial derivatives* between pairs of input and outputs are defined.
The *Jacobian* of all the partials is defines, but ChainRules does not represent Jacobians.
(the gradient isn't, and thus neither is the curl or the div. Though those would be defined if it was  ℝⁿ→ℝ)
The directional derivative/pushforward/ jacobian vector product (jvp) is defined and is represented by change rules as part of the `frule`, and can be used to compute columns of the jacobian
The pullback / vector jacobian product (vjp) is defined and is represented by ChainRules as part of the `rrule`, and can be used to compute the rows of the jacobian.

I *think* you are asking can ChainRules represent Jacobians.
To which the the answer is no.
We have no type for that, and don't support writing rules for that.
AD systems that give back Jacobians do so via either pushing forward all elements of a basis for the input space,
or pulling back all elements of a basis for the output space, and then assembling the results.

**Comment by parth-07** [comment]
> I think you are asking can ChainRules represent Jacobians.
Yes, this is what I was asking. Sorry for the unclear terminology in my previous comments. 

Thank you so much, your reply helped a lot. Thanks again for clearing all my doubts and questions.
