### ISSUE TITLE
Drop Julia 1.0?

### ISSUE THREAD

**Issue by mcabbott** [JuliaDiff/ChainRules.jl#574]
Since LTS is now 1.6, can this package move on from supporting 1.0? It's a pain to figure out what's broken there, always something.

**Comment by oxinabox** [comment]
Yes, let's do it.
We can always backport things if we need to.

**Comment by sethaxen** [comment]
Specifically, are we suggesting updating the lower bound to 1.6, or a lower Julia version? If 1.2 or later, it would be nice to also adopt `test/Project.toml`.

**Comment by oxinabox** [comment]
> Specifically, are we suggesting updating the lower bound to 1.6, or a lower Julia version?

1.6

> If 1.2 or later, it would be nice to also adopt test/Project.toml.

I would rather not.
I have worked on a few packages that use it, and i find them frustrating.
Because information gets duplicated and then out of sync between the main deps and the test deps.

We can think about that at a future time

**Comment by mcabbott** [comment]
ChainRulesCore.jl could similarly drop 1.0. The only incentive there is that it can drop Compat.jl and have zero deps. Some inference/alloc tests could be tidied. But maybe no rush.
