### ISSUE TITLE
ChainRules and ONNX(Runtime)

### ISSUE THREAD

**Issue by dfdx** [JuliaDiff/ChainRules.jl#580]
[ONNXRuntime][1] provides an optimized platform for inference and training of ML models. Surely, types of supported models are limited to the ONNX operator set, but it's rich enough for most conventional deep learning applications, and once [ONNX.jl][2] gets more mature, we will be able to export many Flux/NNlib models to it for inference. But not for training.

Unfortunately, ONNX doesn't support many of the Julia features widely used in ChainRules. Most notably:

* closures, i.e. all pullbacks defined in `rrule`s
* thunks
* `ProjectTo`

The same applies to XLA, although I know much less about it. More generally, once we transform `f(args...)` into `rrule(f, args...)`, the interoperability of the resulted program significantly drops, no matter what operator set we use. I don't have any particular projects where it's a blocker at the moment, but I'm curious if there's a plan for this case, e.g. a version of ChainRules or a dedicated ruleset that can be "lowered" to a list of predefined operations without any advanced features.

[1]: https://onnxruntime.ai/
[2]: https://github.com/FluxML/ONNX.jl

**Comment by oxinabox** [comment]
No concrete thoughts yet.

For `@scalar_rules`
(Which disallow a lot of features of ChainRules)
we can fairly easily do more, and we do have the experimental API function they declare Iirc `derivative_from_output`
that avoids closures.


Re: ProjectTo: I assume onyx only supports dense unstructured arrays. And thus ProjectTo would not be needed. It would always be identity operation.
In general, it's not terrible to replace ProjectTo with the identity operation.


Re: thunks: thunks are a gross and we would like not to need them.

**Comment by dfdx** [comment]
Sounds reasonable. I also thought about extracting forward and backward code directly from `rrule`s. For example, ONNX.jl uses Ghost under the hood, and Ghost now has an experimental function `primitivize!()` which turns every non-primitive function call (e.g. a pullback) into a list of primitive calls (Something similar should also be possible directly on compiled functions using tools like Mixtape.) If thunks and `ProjectTo` can be removed in this scenario, it sounds like a reasonable approach.

I think it's enough for the start, so let's close this issue and come back to it when the ecosystem is ready for concrete actions.
