### ISSUE TITLE
Can we define rules for NamedTuple{T}(...), Val{T}(...)?

### ISSUE THREAD

**Issue by dfdx** [JuliaDiff/ChainRules.jl#584]
On IR level, keyword arguments are passed to functions as named tuples, which leads to code similar to this:

```julia
# mean(x; dims=1)
names = (:dims,)
NT = Core.apply_type(Core.NamedTuple, names)
val = Core.tuple(1)
nt = NT(val)     # i.e. NamedTuple{(:dims,)}((1,))
```
If we want to backpropagate through this code, we need to define an `rrule()` for the last line, i.e. `NT(val)`. However, `typeof(NT)` is generic `UnionAll`, and we can't unambiguously define `rrule(::UnionAll, ...)` (I tried!).

The same applies e.g. to expression:

```julia
T = Val{2}
val = T()
```
The type of `Val{2}` is simply `DataType`, which is a bit too wide for a rule (including `@non_differentiable`, which is probably the right thing for `Val{T}`). 

Is there any workaround for cases like this?

**Comment by simeonschaub** [comment]
Why are you trying to define `rrule(::UnionAll, ...)` here instead of just `rrule(::Type{NamedTuple{names}}, ...) where {names}`?

**Comment by dfdx** [comment]
Interesting. I tried:

```julia
rrule(::Type{NamedTuple}, ...) = ...
# and
rrule(::Type{NamedTuple{names} where names}, ...) = ...
```
but they didn't match. Also, `typeof(NamedTuple((:dims,)))` has an empty `.parameters` field, so I've got convinced fine-grained type information has been lost... I'm glad I was wrong! 

Thanks!
