### ISSUE TITLE
using AD in rule definitions themselver for implicit function

### ISSUE THREAD

**Issue by tpapp** [JuliaDiff/ChainRules.jl#585]
I have a computation which involves a *user-defined* implicit function `g: R^n \times R^m \to R^m`, used as `g(x, y) = 0` where `x \in R^n` and `y \in R^m`. This implicitly defines `y = f(x)`. The implementation is via multidimensional rootfinding, as in
```julia
function solve_y(g, x)
   ...
end
```
I want to define forward and reverse rules for this. The algebra itself is straightforward (unless I made a mistake :wink:), ie
```latex
\dot{y} = g_y^{-1} g_x \dot{x}
\bar{x} = g_x^{*} {g_y^{-1}}^{*} \bar{y}
```
where I have omitted arguments, ie `g_x = g_x(x, y)`. But to actually obtain these derivatives I would need to use AD again (remember, user-supplied `g`, no closed form).

I could just call `ForwardDiff.jacobian` within the rules. Just wondering if this is the recommended method.

**Comment by sethaxen** [comment]
I think you are looking for `frule_via_ad` or [`rrule_via_ad`](https://juliadiff.org/ChainRulesCore.jl/stable/api.html#ChainRulesCore.rrule_via_ad)

**Comment by oxinabox** [comment]
https://juliadiff.org/ChainRulesCore.jl/dev/rule_author/superpowers/ruleconfig.html#Writing-rules-that-call-back-into-AD
