### ISSUE TITLE
Rule for `svdvals`

### ISSUE THREAD

**Issue by mcabbott** [JuliaDiff/ChainRules.jl#587]
Requested here: https://discourse.julialang.org/t/implementation-of-spectral-normalization-for-machine-learning/76074

The workaround is to call `svd(X).S`, which is slower forwards. But it looks like the gradient calculation with something like `svd_rev((; U=NoTangent(), s=s, V=NoTangnet(), Vt=NoTangent()), NoTangent(), S̄, NoTangent())` is probably fairly efficient, and could easily be extracted to its own rule:

https://github.com/JuliaDiff/ChainRules.jl/blob/3590f9421950508a97d5a9dbc207208e331c8b75/src/rulesets/LinearAlgebra/factorization.jl#L221-L225

**Comment by sethaxen** [comment]
I agree, yes, this should be its own rule. We already did that for Hermitian matrices.

**Comment by sethaxen** [comment]
Ah, no, it goes via the rrule for `eigvals`, which uses the pullback for `eigen`. So yeah, just using the pullback for `svd` might be best.
