### ISSUE TITLE
`frule` for `LinearAlgebra.exp!` often gives wrong result

### ISSUE THREAD

**Issue by StevenWhitaker** [JuliaDiff/ChainRules.jl#595]
On Julia 1.7.0 with ChainRules v1.27.0 and FiniteDifferences v0.12.24 I noticed the following when comparing a manually computed Jacobian using ChainRules to one computed using FiniteDifferences.

```julia
julia> using ChainRulesCore, ChainRules, FiniteDifferences, LinearAlgebra, Random

julia> function compare(A)
           ΔA = ((tmp = zeros(3, 3); tmp[i] = 1; tmp) for i = 1:9)
           Ȧ = reduce(hcat, (vec(ChainRulesCore.frule((NoTangent(), ΔA), LinearAlgebra.exp!, copy(A))[2]) for ΔA in ΔA))
           dA = jacobian(central_fdm(12, 1), LinearAlgebra.exp!, copy(A))[1] # Similar results if I use exp here
           norm(dA - Ȧ) / norm(dA)
       end

julia> Random.seed!(4); A = randn(3, 3)
3×3 Matrix{Float64}:
 -1.43958    0.723766  0.804293
  0.401951  -1.78305   0.471269
  0.748248  -0.853744  0.788465

julia> compare(A)
2.236952800467401e-11 # Good

julia> Random.seed!(5); A = randn(3, 3)
3×3 Matrix{Float64}:
 0.378172   0.59316   -0.650402
 0.949351  -0.553783   0.00584074
 2.48586    0.858478  -0.54068

julia> compare(A)
1.3838115170508762 # Bad
```

In case this info helps, I tried 1000 different random seeds, and 773 of them failed with relative error >= 1e-8 (749 of them failed with relative error >= 0.01). In 323 of the failure cases the primal input was modified in the `frule` (all for cases with relative error >= 0.01), whereas the primal input was modified in just 2 of the successful cases.

Am I doing something wrong? I noticed in #353 commentary about FiniteDifferences hitting multiple branches in `exp`, but the `rtol` used in the tests is `1e-8`, not >1, so I'm not sure that's the primary reason for the failure I'm seeing.

**Comment by sethaxen** [comment]
Thanks! Definitely a bug that happens for certain matrices `A` (the tangent does not seem to matter). Another MWE:
```julia
julia> using Random, LinearAlgebra, ChainRulesTestUtils

julia> A = randn(MersenneTwister(8), 3, 3)
3×3 Matrix{Float64}:
 -0.00762343  -0.567237   0.441904
  2.09084     -1.25408   -0.0414577
  2.33979     -0.665049   0.638727

julia> test_frule(LinearAlgebra.exp!, A)
test_frule: exp! on Matrix{Float64}: Test Failed at /Users/sethaxen/.julia/packages/ChainRulesTestUtils/fCvaU/src/check_result.jl:24
  Expression: isapprox(actual, expected; kwargs...)
   Evaluated: isapprox([19.845199932019106 -3.181901627327679 9.853336201221664; 12.597308052683074 -2.4573738413477333 6.12060850384048; -4.973701720876723 0.2838380903601535 3.597224878529165], [12.221166968175835 -3.5103422690750716 10.304930740557078; 11.182649163463585 -3.3551773909402933 7.355057377873935; -5.677277425437907 1.2049782600627865 2.330688957798258]; rtol = 1.0e-9, atol = 1.0e-9)
```

**Comment by sethaxen** [comment]
Seems to be related to the matrix balancing code (hence why it's primal specific; balancing is a no-op for some matrices). Shouldn't be hard to narrow down the bug. 🤞

**Comment by StevenWhitaker** [comment]
Thanks for verifying it's not user error :+1: 

> Seems to be related to the matrix balancing code

I commented out that code in both `_matfun!` and `_matfun_frechet!`; the primal computation still gives the correct result, but the pushforward is still wrong. I have also found instances of `A` where the balancing is a no-op, and yet the pushforward is wrong. Does that mean the problem is not related to matrix balancing?

**Comment by sethaxen** [comment]
> I commented out that code in both _matfun! and _matfun_frechet!; the primal computation still gives the correct result, but the pushforward is still wrong.

This is different from what I'm seeing. If I comment out `LAPACK.gebal!`, `_balance!`, and `_unbalance!` everywhere, all tests pass.

> I have also found instances of A where the balancing is a no-op, and yet the pushforward is wrong.

Can you share one of these examples?

**Comment by sethaxen** [comment]
Ah, figured it out. The issue is that when no squaring is necessary, we end up using an intermediate for computing the Fréchet derivative that has been un-balanced, when it should still be balanced. I'll open a PR to fix.

**Comment by StevenWhitaker** [comment]
Thanks for your work on this @sethaxen. I see #596 fixes the `MersenneTwister(8)` case, but it looks like, e.g., `MersenneTwister(3)` fails. Not sure what's different between the two cases.

**Comment by StevenWhitaker** [comment]
>>I have also found instances of A where the balancing is a no-op, and yet the pushforward is wrong.
>
>Can you share one of these examples?

```julia
pkg> add ChainRules#fixexp

julia> using ChainRulesCore, ChainRules, ChainRulesTestUtils, LinearAlgebra, Random

julia> function test_seed(seed)

           A = randn(MersenneTwister(seed), 3, 3)
           A0 = copy(A)
           ChainRulesCore.frule((NoTangent(), ones(3, 3)), LinearAlgebra.exp!, A)
           @show A == A0
           test_frule(LinearAlgebra.exp!, copy(A0))

       end

julia> test_seed(18)
A == A0 = true
test_frule: exp! on Matrix{Float64}: Test Failed at /home/steven/.julia/packages/ChainRulesTestUtils/fCvaU/src/check_result.jl:24
  Expression: isapprox(actual, expected; kwargs...)
   Evaluated: isapprox([-49.423878705517254 9.694894942785455 8.671753156406332; -1.8709936610520406 22.284806039679847 -17.976586983739555; -29.781909495530332 4.409925826459972 -7.671989120111034], [-49.42387861618013 9.694894871745788 8.671753164536202; -1.8709936886668288 22.284806061617306 -17.97658698650175; -29.781909446072973 4.409925787130784 -7.671989115659726]; rtol = 1.0e-9, atol = 1.0e-9)
```

(I also explicity checked that `LAPACK.gebal!('B', A)` did not modify `A`.)
