### ISSUE TITLE
Adding compatibility with Compat v4

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/ChainRules.jl#623]
Compat v4 is out, but CompatHelper doesn't seem to open PRs for it. We need to do so manually.

**Comment by devmotion** [comment]
See https://github.com/JuliaDiff/ChainRulesCore.jl/pull/555. I think it might be due to its dependency on Compat@3 via Mocking that CompatHelper doesn't open PRs. I'll made a PR to Mocking as well which hopefully fixes the general issue.

**Comment by devmotion** [comment]
So I guess this issue can be closed?
