### ISSUE TITLE
rrule for QR-decomposition

### ISSUE THREAD

**Issue by oschulz** [JuliaDiff/ChainRules.jl#651]
Would be nice to have an `rrule` for QR-decomposition.

According to https://rkube.github.io/jekyll/update/2021/07/06/backpropagating-through-qr.html, Pytorch [uses](https://github.com/pytorch/pytorch/blob/b162d95e461a5ea22f6840bf492a5dbb2ebbd151/torch/csrc/autograd/FunctionsManual.cpp) the method described in  https://arxiv.org/abs/1710.08717 .

**Comment by oschulz** [comment]
CC @cscherrer

**Comment by sethaxen** [comment]
We already have #516, #306, and #469. 2 of these are by the author of the linked blog post.

QR rules in Julia are trickier than in PyTorch, jax, etc for reasons summarized in https://github.com/JuliaDiff/ChainRules.jl/pull/469#issuecomment-939147971. I'll allocate some time in the coming month to dig into these proposals and push this forward.

**Comment by oschulz** [comment]
Oh, right - thanks @sethaxen ! I'll close this issue, then.

**Comment by oschulz** [comment]
Sorry, I somehow overlooked the existing PRs.

**Comment by wangleiphy** [comment]
@giggleliu anything you can help with here ?

**Comment by GiggleLiu** [comment]
> @GiggleLiu anything you can help with here ?

I probably can help with testing complex valued backward rule, and thin qr. The general purposed qr backward with pivot is a bit tricky. Since I do not have time to dive into all of these issues at the moment, I would suggest copy-paste the part that you need?
