### ISSUE TITLE
Make `test_utils` available as a stand alone package

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDiff/ChainRules.jl#69]
- The [test utils](https://github.com/JuliaDiff/ChainRules.jl/blob/91c5d927a17166a8dd5dd627f887d622aa4d645b/test/test_util.jl) that use finite differences to check correctness are nice, and probably could be useful for people adding sensitivites in their own packages.
- We could make this a submodule, like `ChainRules.TestUtils` so people can use this functionality in their own tests 
- These utils depend on [FDM/FiniteDifferences.jl](https://github.com/JuliaDiff/FiniteDifferences.jl), which is probably not a dependency we want to add to ChainRulesCore.jl, but is less bad here where we already have heavier dependencies (and it'd be a test-only dependency for users)
- If this functionality does turn out to be useful and widely used, then we can easily make this its own package in future

**Comment by oxinabox** [comment]
I'm not super against adding a FiniteDifferences.jl dependency to ChainRules.jl
because it means that we can probably do something like Zygote's `validate` flag,
where it checked custom sensitivies everytime they are called.

Though perhaps that is better done in the AD only

**Comment by nickrobinson251** [comment]
I wonder what @willtebbutt thinks?

**Comment by willtebbutt** [comment]
I guess there are two options here:

1. Add a `ChainRules.TestUtil` module, and make `FiniteDifferences` a dependency.
2. Create another repo called `ChainRulesTestUtil` or something. This might be preferable from a package maintainer's point of view as they could then just add `ChainRulesCore` to their `[deps]`, and `ChainRulesTestUtil` to their `[extras]`, and not depend on `ChainRules` at all.

> because it means that we can probably do something like Zygote's validate flag

This is something that we could think about doing, but I expect that the merits are much less substantial than in an AD-package's case.

**Comment by oxinabox** [comment]
Option 3.
We could make `TestUtil` a submodule of FDM.
We would want to make it a bit more general so you need to pass in that you are using something to get  the rules and stuff. (Possibly could be made general enough that you easily use it for testing both chainrules and an AD system). This feels good if we can get a good abstraction.
Maybe something that takes in such a thing and returns a named tuple of closures over it, as a kind of fake module?

**Comment by willtebbutt** [comment]
I would be pro- this third option if it could be done in a way that has a simple API that would play nicely with both ChainRules and AD packages. Seems like a common-enough problem.

**Comment by willtebbutt** [comment]
Just bumping this. Is anyone keen to work on it? I would love to see it done, as I regularly implement custom adjoints and having something standalone to help out with this would be fantastic. Alas, I don't really have time to work on this at the minute.

**Comment by oxinabox** [comment]
I have limitted time to do ChainRules stuff right now,
In a few weeks will have plenty of time and sometime after that will have both time and people.

What little time I have right now, is direct at the Composite PR in ChainRulesCore, and the Zygote PR.

**Comment by oxinabox** [comment]
@mattBrzezinski is this a thing you might have time/interest in doing?

**Comment by mattBrzezinski** [comment]
I should have some free time for this in the next while.

**Comment by mattBrzezinski** [comment]
Some quick thoughts on this, the second option seems like the most simple route to go down, and it would be nice and clean to just add this new package as a test dependency wherever you might need it.

The third option of a submodule in FDM seems a bit strange to me, as I don't see how the two are directly connected? If we did a new package, are there other utilities in our differential tools that can be pulled out and used across the board?

If so, it would be nice to have a `JuliaDiff/DiffTestingUtils` package which could encapsulate all sorts of generic tools and introduce this package as a test dependency in other packages.

**Comment by oxinabox** [comment]
I think this should be a new package.
Maybe `TestingDiffs.jl` or `DiffTest.jl`

I think it would be good to have this as a test dependency, here and also in other places,
like when ever someone implements ChainRules they should be able to depend on this and test it.

According to @willtebbutt  there are many copies of similar code to this, in his repos and also in Nabla.

**Comment by willtebbutt** [comment]
Separate package sounds good to me.

**Comment by nickrobinson251** [comment]
What a great thread! Time allowing, very happy to help :)

**Comment by oxinabox** [comment]
I ha e created an empty JuliaDiff/DiffTest.jl repo

**Comment by mattBrzezinski** [comment]
Would a new repo be most appropriate? Or fill into https://github.com/JuliaDiff/DiffTests.jl ?

If not, these package names are very very similar probably should pick something different.

**Comment by willtebbutt** [comment]
Good point. They probably shouldn't be in the same repo as the intentions of the packages are somewhat different. Jarrett wrote DiffTests many moons ago to constitute a series of quite challenging problems for an AD system to get right (e.g. does a forwards-mode package successfully deal with problems where perturbation confusion could be a problem), whereas we're writing a tool for checking that an AD tool / frule / rrule returns the correct thing.

I think your idea of having different names is probably a good move. We should also reference each package in their respective readmes, explaining what the relationship between the two is to avoid confusion.

**Comment by nickrobinson251** [comment]
AutoDiffTests might be a better name for the existing package. But even then the names are quite similar. AutoDiffChallenges and DiffTest? 

Alternative we could name the new one something like ChainRulesTest. Might be a better way to go.

 Naming things is difficult

**Comment by oxinabox** [comment]
How about a more different name.
The operation we are doing is basically [Grad Check](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.check_grad.html)
but not just on gradients.

Maybe something super verbose: *CheckMyDerviativesAreCorrect.jl*

ChainRulesTest is fine though.

**Comment by mattBrzezinski** [comment]
I think `ChainRulesTests.jl` is a good name, it's explicit and unique enough. I don't have the perms to make it repo, if someone else could that'd be great.

**Comment by willtebbutt** [comment]
> I think ChainRulesTests.jl is a good name, it's explicit and unique enough. I don't have the perms to make it repo, if someone else could that'd be great.

Have modified your permissions :)

**Comment by nickrobinson251** [comment]
https://github.com/JuliaDiff/ChainRulesTestUtils.jl
