### ISSUE TITLE
Writie initial Getting Started documentation

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDiff/ChainRules.jl#72]
We currently have some deployed docs at http://www.juliadiff.org/ChainRules.jl/latest/
crying out for "getting started" documentation.

Currently 4 sections are suggested
- Forward-Mode vs. Reverse-Mode Chain Rule Evaluation
- Real Scalar Differentiation Rules
- Complex Scalar Differentiation Rules
- Non-Scalar Differentiation Rules
...but some other categorisation might work fine.

Adding even one section would be a great start.

Lots of things have docstrings now... but adding more would also be helpful!

**Comment by davidcode00** [comment]
Hey, I want to contribute, can you help me how to get started?

**Comment by oxinabox** [comment]
Some links:
 - source code of https://github.com/JuliaDiff/ChainRulesCore.jl
 - The source for the micro-ADs linked in https://github.com/JuliaDiff/ChainRules.jl/issues/8
 - Instructions on porting things from Nabla https://github.com/invenia/Nabla.jl/issues/177
     - We need to write similar ones for Zygote and Tracker.

**Comment by oxinabox** [comment]
Probably not a good first issue

**Comment by nickrobinson251** [comment]
:shrug: trying to write some documentation was how I got started with the package

**Comment by oxinabox** [comment]
Closed by #103
