### ISSUE TITLE
Reconsider giving `zero` as the derivative of one

### ISSUE THREAD

**Issue by Keno** [JuliaDiff/ChainRules.jl#725]
I'd like to reconsider the discussion in #187. Because of this change, we have the following unfortunate situation:

```
julia> using Diffractor, ZeroBundle
julia> using Diffractor: ZeroBundle
julia> using ChainRules: ZeroTangent
julia> Base.return_types(Diffractor.∂☆{2}(), Tuple{
	typeof(ZeroBundle{2}(/)),
	Diffractor.TangentBundle{2, Float64, Diffractor.TaylorTangent{Tuple{Float64, ZeroTangent}}},
	Diffractor.TangentBundle{2, Float64, Diffractor.TaylorTangent{Tuple{ZeroTangent, ZeroTangent}}},
})[1]

Diffractor.TangentBundle{2, Float64, Diffractor.TaylorTangent{Tuple{Float64, Float64}}}
```

vs with that rule set of ZeroTangent:

```
Diffractor.TangentBundle{2, Float64, Diffractor.TaylorTangent{Tuple{Float64, ZeroTangent}}}
```

i.e. because of said rule, we can't concluded that the second order derivative remains zero at type-level. This is unfortunate, because it introduces significant additional code generation. I of course can see both arguments - in general ChainRules has a bit of a type-stability problem because of these types, but I don't think there's any good reason to not return the sentinel type just for these particular functions.

**Comment by oxinabox** [comment]
Yes. I am happy to see it switched back.
We should also switch it back for `@scalar_rule` that change was motivated by ForwardDiff2.jl but since that's dead, I no longer see such need for it.

It's related to https://github.com/JuliaLang/julia/issues/38241 in general.
`map`s are the place we get bitten.

**Comment by oxinabox** [comment]
> We should also switch it back for @scalar_rule that change was motivated by ForwardDiff2.jl but since that's dead, I no longer see such need for it.

Looks like that was already done, or never existed in first place
