### ISSUE TITLE
muladd test code doesn't test complex numbers.

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#753]
The muladd code looks like it tests with complex number but actually never generates complex number, just generating floats again a second time

https://github.com/JuliaDiff/ChainRules.jl/blob/01ea92b83d3f7b530303942eaa9e7df89028fa97/test/rulesets/Base/base.jl#L151-L154

This PR should be small and not at all difficult.

**Comment by not-physicist** [comment]
#786 should fix this.

**Comment by mcabbott** [comment]
Indeed. (If you say #753 in the first message of a PR, github will automatically close the issue.)
