### ISSUE TITLE
Add FiniteDifferences based tests to some scalar functions

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#76]
As found for `hypot` 
https://github.com/JuliaDiff/ChainRules.jl/pull/74
we are not testing some of our simpler scalar rules with FiniteDifferences.
We have easy helpers for how to do that in `test/test_utils.jl`
but we just are not using them

**Comment by oxinabox** [comment]
Infact, basically all out scalar tests are bad.

To define a scalar rule you provide the same things as in the source,
so if you were wrong in one place you are wrong in the other too and never catch it.

For example

### Source
```
@scalar_rule(sin(x), cos(x))
@scalar_rule(cos(x), -sin(x))
@scalar_rule(tan(x), 1 + Ω^2)
```

### Tests

```
test_scalar(sin, cos, x)
test_scalar(cos, x -> -sin(x), x)
test_scalar(tan, x -> 1 + tan(x)^2, x)
```


Those are way too similar.

I am going fix them to use FiniteDiferences.

**Comment by simeonschaub** [comment]
This would be great to have! I've been meaning to add a test based on FDM for Wirtinger derivatives too, since a lot of rules aren't written with complex differentiation in mind, and we then just assume them to be holomorphic, which is often wrong.
