### ISSUE TITLE
SparseInverseSubset.jl dependency causes issues on non-GPL Julia builds

### ISSUE THREAD

**Issue by ElOceanografo** [JuliaDiff/ChainRules.jl#763]
ChainRules depends on SparseInverseSubset.jl to be able to differentiate through determinants of sparse matrices. However, this requires the `CHOLMOD` type for sparse Cholesky decompositions from SuiteSparse.jl, which is unavailable on non-GPL Julia builds, causing errors. See [here](https://github.com/ElOceanografo/SparseInverseSubset.jl/pull/2) and [here](https://github.com/ElOceanografo/SparseInverseSubset.jl/issues/3).

I think the cleanest way to handle this would be to add conditional statements for importing SparseInverseSubset.jl, and for the `rrule`s for `logdet` and `logabsdet` of sparse matrices so that these are omitted if `Base.USE_GPL_LIBS == false`. If that sound like the right approach I will make a PR.

**Comment by oxinabox** [comment]
I think that does indeed sound right
wrap it in top level
```
if Base.USE_GPL_LIBS  # don't define these if we don't have CHOLMOD from SuiteSparse.jl
    using SparseInveserSubset
    function rrule(...)
    ...
end
```

that way we will get the usual behavours as if the rrule had not being defined -- because it wouldn't have been defined.
