### ISSUE TITLE
`∇eachslice` causes `UndefRefError` when input array contains references

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaDiff/ChainRules.jl#807]
https://github.com/JuliaDiff/ChainRules.jl/blob/30f9b121e69fe20f3a176e92e3ceb91f53606f8c/src/rulesets/Base/indexing.jl#L264-L282

1. `similar` makes `dx` an uninitialized array.
2. When `dys[i]` is zero, presumably the intent of `_zero_fill!(slice)` is to populate the array with zeros.
3. `_zero_fill!` on an uninitialized array calls `map!(zero, dx, dx)`
4. `map!` attempts to map `zero` onto the elements of `dx`, which are `#undef` - error

So this branch never works when the input array has references rather than inline values.

**Comment by BioTurboNick** [comment]
Here, `dys[i1]` elements are of type `ChainRulesCore.Tangent{Any, @NamedTuple{μ::Float64, σ::Float64}}`, and x elements are of type `Distributions.Normal{Float64}`, which get promoted to `Any` for `dx`

Based on that comment, should the `undef` positions be filled with `ZeroTangent()`?

Or is there some upstream issue that's only surfacing here?

**Comment by mcabbott** [comment]
I wonder why this code does `T = promote_type(eltype(dys[i1]), eltype(x))`. It seems that if it did `T = eltype(dys[i1])` then this would just work. 

I'm also not entirely sure what the second method of `_zero_fill!` was intended for, perhaps arrays of arrays? As you say it will fail for `dx` made by `similar` with reference types:
```
_zero_fill!(dx::AbstractArray{<:Number}) = fill!(dx, zero(eltype(dx)))
_zero_fill!(dx::AbstractArray) = map!(zero, dx, dx)
```
The tests for this are not extensive:

https://github.com/JuliaDiff/ChainRules.jl/blob/30f9b121e69fe20f3a176e92e3ceb91f53606f8c/test/rulesets/Base/indexing.jl#L232-L236

**Comment by BioTurboNick** [comment]
Unfortunately that doesn't just work, because the output needs to store different `AbstractTangent` types.

So I think `T = promote_type(eltype.(dys)...)` does that. But if there are mixed `AbstractTangent` types in the input, that means the array is abstractly typed and would still start with `undef`.

**Comment by BioTurboNick** [comment]
So there's another case where an unexpected situation occurs.

Zygote uses `wrap_chainrules_input` to convert an `Array{Union{Float64, Nothing}}}` to `Array{Any}` via replacing `nothing` with `ZeroTangent`. But seems like the intent inside `∇eachslice` is that `zero(T)` is used instead of `ZeroTangent()` wherever possible.

I'm wondering if there's a function where the NamedTuple tangents are decomposed into individual values, and the `ZeroTangent`s there should be turned into 0s but instead are turned into `nothing`, which causes the above.

However, given that this occurs, the following appears to at least intercept it and transform it prior to being passed back to ChainRules:
```
@inline Zygote.wrap_chainrules_input(dxs::AbstractArray{<:Union{Nothing,T}}) where T <: Number = map(x -> x === nothing ? zero(T) : x, dxs)
```
