### ISSUE TITLE
Add tests that check for things not being incredibly generally defined?

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#81]
See

https://github.com/JuliaDiff/ChainRules.jl/pull/77#issuecomment-519857792

**Comment by nickrobinson251** [comment]
related to https://github.com/JuliaDiff/ChainRulesCore.jl/issues/155

**Comment by mzgubic** [comment]
Should we close this now that we have `ProjectTo`? Or did I misunderstand?

**Comment by nickrobinson251** [comment]
Xref #563
