### ISSUE TITLE
stop defining derviative of `abs(::Complex)`?

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/ChainRules.jl#88]
Currently it `sgn` which is apparently not correct.

[Wikipedia](https://en.wikipedia.org/wiki/Absolute_value#Derivative)

> The complex absolute value function is continuous everywhere but complex differentiable nowhere because it violates the Cauchy–Riemann equations.[13]

**Comment by simeonschaub** [comment]
Differentiable here means holomorphic. The Wirtinger derivative is defined everywhere except zero. I actually added the right rule in  #55

**Comment by nickrobinson251** [comment]
sorry that the ground moved from under that PR a bit... what's the status with #55?

**Comment by simeonschaub** [comment]
It's basically ready to merge, but one inconsistency at the moment is that it returns a one-tuple if called with only one argument, which is inconsistent with the other one-arg rules
